version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/logs
      - ./static:/app/static
      - ./static/images:/app/static/images
      - ./static/images/saved:/app/static/images/saved
      - /home/azureuser/stable-diffusion/StableDiffusion_GUI_App-main/starter_files/models/stable-diffusion-v1-4:/app/stable-diffusion-v1-4
    environment:
      FLASK_ENV: development
      PYTHONPATH: /app
      
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=8000"]
