version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8000:8000" # Expose le port de l'application Flask
    volumes:
      - .:/app # Montage du répertoire local pour synchroniser les fichiers du projet
      - ./logs:/logs # Montage des logs
      - ./static:/app/static # Dossier static
      - ./static/images:/app/static/images # Images générées
      - ./static/images/saved:/app/static/images/saved # Images sauvegardées
      - /opt/stable-diffusion/stable-diffusion-v1-4:/opt/stable-diffusion/stable-diffusion-v1-4:ro

    environment:
      FLASK_ENV: development
      PYTHONPATH: /app
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=8000"]
