FROM python:3.11.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    libfreetype6-dev \
    liblcms2-dev \
    libopenjp2-7-dev \
    libwebp-dev \
    python3-tk \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR /app

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt \
    && pip install \
    Pillow>=10.0.1 \
    Flask>=2.3.3 \
    werkzeug>=3.0.1 \
    torch>=2.2.0 \
    transformers>=4.37.2 \
    accelerate>=0.27.0 \
    diffusers>=0.25.0 \
    huggingface_hub>=0.20.3 \
    opencensus-ext-azure>=1.1.13 \
    opencensus-ext-flask>=0.8.3

COPY . .

EXPOSE 8000

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=8000"]