services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/logs
      - ./:/app  # Monte le répertoire actuel dans /app dans le conteneur
      - ./static:/app/static
    environment:
      - FLASK_ENV=development