# Utilise une image de base Python Slim
FROM python:3.11.10-slim

# Configuration de l'environnement Python
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Installation des dépendances système
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    libfreetype6-dev \
    liblcms2-dev \
    libopenjp2-7-dev \
    libwebp-dev \
    python3-tk \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers de dépendances Python
COPY requirements.txt .

# Installe les dépendances Python
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r requirements.txt

# Copie les fichiers de l'application
COPY . .

# Expose le port pour Flask
EXPOSE 8000

# Définit l'utilisateur par défaut pour exécuter l'application
USER root

# Commande par défaut pour démarrer l'application Flask
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=8000"]
